# Generated by Django 4.0 on 2022-04-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transformer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('TimeStamp', models.DateTimeField()),
                ('Transformer_ID', models.CharField(max_length=50)),
                ('Transformer_Type', models.CharField(choices=[('01', 'Resedential Rural'), ('02', 'Resedential Urban'), ('03', 'Industrial')], max_length=2)),
                ('Current_Input', models.FloatField()),
                ('Voltage_Input', models.FloatField()),
                ('Oil_Temprature', models.FloatField()),
                ('Winding_Temprature', models.FloatField()),
                ('Oil_TankLevel', models.FloatField()),
                ('Moisture_Level', models.FloatField()),
                ('Tapping_Ratio', models.FloatField()),
                ('Overall_Health', models.FloatField()),
            ],
        ),
    ]
