# Generated by Django 4.0 on 2022-05-22 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transformer',
            name='Current_Input',
        ),
        migrations.RemoveField(
            model_name='transformer',
            name='Moisture_Level',
        ),
        migrations.RemoveField(
            model_name='transformer',
            name='Oil_TankLevel',
        ),
        migrations.RemoveField(
            model_name='transformer',
            name='Oil_Temprature',
        ),
        migrations.RemoveField(
            model_name='transformer',
            name='Overall_Health',
        ),
        migrations.RemoveField(
            model_name='transformer',
            name='Tapping_Ratio',
        ),
        migrations.RemoveField(
            model_name='transformer',
            name='TimeStamp',
        ),
        migrations.RemoveField(
            model_name='transformer',
            name='Voltage_Input',
        ),
        migrations.RemoveField(
            model_name='transformer',
            name='Winding_Temprature',
        ),
        migrations.AddField(
            model_name='transformer',
            name='accounts',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transformer',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transformer',
            name='longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transformer',
            name='Transformer_ID',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='TransData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
                ('Current_Input', models.FloatField()),
                ('Voltage_Input', models.FloatField()),
                ('Oil_Temprature', models.FloatField()),
                ('Winding_Temprature', models.FloatField()),
                ('Oil_TankLevel', models.FloatField()),
                ('Moisture_Level', models.FloatField()),
                ('Tapping_Ratio', models.FloatField()),
                ('Overall_Health', models.FloatField()),
                ('transformer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transformer', to='backend.transformer')),
            ],
        ),
    ]
